<?php

namespace App\Exceptions;

use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Illuminate\Http\Response;
use Illuminate\Validation\UnauthorizedException;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * The list of the inputs that are never flashed to the session on validation exceptions.
     *
     * @var array<int, string>
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     */
    public function register(): void
    {
        $this->reportable(function (Throwable $e) {
            //
        });

        $this->renderable(function (\Spatie\Permission\Exceptions\UnauthorizedException $e, $request) {
            return response()->json([
                'message' => 'You do not have the required authorization.',
                'statusCode'  => 403,
            ]);
        });

    }

    public function render($request, Throwable $e)
    {
        if($request->is('api/**')) {

            if ($e instanceof AuthorizationException) {
                return response()->json([
                    'message' => "You don't have permissions",
                    'statusCode' => Response::HTTP_FORBIDDEN
                ], Response::HTTP_FORBIDDEN);
            }

            if ($e instanceof \Symfony\Component\HttpKernel\Exception\HttpExceptionInterface) {
                return response()->json([
                    'message' => $e->getMessage(),
                    'statusCode' => $e->getStatusCode()
                ], $e->getStatusCode());
            }

            if ($e instanceof UnauthorizedException) {
                return response()->json([
                    'message' => "Unauthorized",
                    'statusCode' => Response::HTTP_UNAUTHORIZED
                ], Response::HTTP_UNAUTHORIZED);
            }

        }
        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }

}
